### POST complete
POST https://localhost:3000/safebox/
Content-Type: application/json

{
  "name": "tes2t-name",
  "password": "AA@01abcQW12"
}

### POST missing name
POST https://localhost:3000/safebox/
Content-Type: application/json

{
  "name": "",
  "password": "1234"
}

### POST missing pass
POST https://localhost:3000/safebox/
Content-Type: application/json

{
  "name": "test",
  "password": ""
}

### PUT with Basic auth and some items
PUT https://localhost:3000/safebox/763a9a8c-5cb7-49be-bb45-d218f5e42241/items
Content-Type: application/json
Authorization: Basic test-name:AA@01abcQW12

{
  "items": [
    "item0",
    "item1",
    "item2"
    ]
}

### PUT with Basic auth but miss items
PUT https://localhost:3000/safebox/763a9a8c-5cb7-49be-bb45-d218f5e42241/items
Content-Type: application/json
Authorization: Basic test-name:AA@01abcQW12

{
  "items": [
    ]
}

### GET
GET https://localhost:3000/safebox/763a9a8c-5cb7-49be-bb45-d218f5e42241/items
Content-Type: application/json
Authorization: Basic test-name:AA@01abcQW12
